//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yased_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int Id { get; set; }
        public string image { get; set; }
        public Nullable<int> insight_id { get; set; }
        public Nullable<int> news_id { get; set; }
        public Nullable<int> united_id { get; set; }
        public Nullable<int> sort { get; set; }
    }
}
