//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yased_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberUser
    {
        public int ID { get; set; }
        public Nullable<int> FK_MemberStatusID { get; set; }
        public Nullable<int> FK_CompanyID { get; set; }
        public Nullable<int> FK_MemberRolesID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PhotoPath { get; set; }
        public string Title { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string LoginKey { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string DeviceToken { get; set; }
        public Nullable<bool> IsIOS { get; set; }
        public string Version { get; set; }
        public string Model { get; set; }
        public string Uuid { get; set; }
        public Nullable<System.DateTime> TokenUpdateDate { get; set; }
        public string ResetGuid { get; set; }
        public Nullable<int> ResetCount { get; set; }
        public string DocGuid { get; set; }
        public string Company { get; set; }
        public string oldPassword { get; set; }
        public string newPassword { get; set; }
        public string newPasswordRepeat { get; set; }
        public string Lang { get; set; }
        public string ContactType { get; set; }
    }
}
