//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yased_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string name_en { get; set; }
        public string title { get; set; }
        public string title_en { get; set; }
        public string label { get; set; }
        public string label_en { get; set; }
        public string image { get; set; }
    }
}
